[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  # Disable turbopack on Netlify to avoid css/postcss crash
  NEXT_DISABLE_TURBOPACK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

